K_d: 0
K_i: 0.01
K_p: 4
db_path: /home/pi/piggia/temps.db
delay_time: 0
max_entries: 10000
max_error_accumulation: 10
max_i: 2500
plot_interval: 2
relay_pin: 18
set_point: 98
seven_segment_enabled: false
seven_segment_spi_bus: 0
seven_segment_spi_device: 0
